name: Build Cipher EXE

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
    
    - name: Build Cipher
      shell: cmd
      run: |
        cl /EHsc /std:c++17 /O2 /MT /DWIN32 /D_WIN32_WINNT=0x0A00 src\main_simple.cpp /Fe:Cipher.exe user32.lib gdi32.lib shell32.lib advapi32.lib ole32.lib pdh.lib winmm.lib psapi.lib comctl32.lib
    
    - name: Test EXE
      run: |
        if (Test-Path "Cipher.exe") {
          $size = (Get-Item "Cipher.exe").Length
          Write-Host "✓ Cipher.exe created - Size: $size bytes"
        } else {
          Write-Host "✗ Build failed"
          exit 1
        }
    
    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: Cipher-EXE
        path: Cipher.exe
        
    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0-${{ github.run_number }}
        name: Cipher v1.0 - Download Ready
        body: |
          🚀 **Cipher.exe - Ready to Download and Run!**
          
          **Download**: Click Cipher.exe below
          **Usage**: Double-click to run
          **Requirements**: Windows 10/11
          
          No installation needed!
        files: Cipher.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
